version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: './server'
      args:
        NODE_ENV: 'production'
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 80:80
