export const DATA_REQUEST = 'DATA_REQUEST'
export const DATA_SUCCESS = 'DATA_SUCCESS'
export const DATA_FAIL = 'DATA_FAIL'
export const DATA_SETS = 'DATA_SETS'
export const DATA_SOURCES = 'DATA_SOURCES'
export const DATA_SOURCES_FILTERED = 'DATA_SOURCES_FILTERED'
export const DATA_TYPES = 'DATA_TYPES'
export const DATA_TYPES_FILTERED = 'DATA_TYPES_FILTERED'
export const DATA_RESET = 'DATA_RESET'

export const SENSORS_REQUEST = 'SENSORS_REQUEST'
export const SENSORS_SUCCESS = 'SENSORS_SUCCESS'
export const SENSORS_FAIL = 'SENSORS_FAIL'
export const SENSORS_RESET = 'SENSORS_RESET'

export const DEVICES_REQUEST = 'DEVICES_REQUEST'
export const DEVICES_SUCCESS = 'DEVICES_SUCCESS'
export const DEVICES_FAIL = 'DEVICES_FAIL'
export const DEVICES_RESET = 'DEVICES_RESET'

export const DATE_RANGE_UPDATE = 'DATE_RANGE_UPDATE'
export const DATE_RANGE_RESET = 'DATE_RANGE_RESET'

export const HOT_BUTTON_SELECTION = 'HOT_BUTTON_SELECTION'
export const HOT_BUTTON_RESET = 'HOT_BUTTON_RESET'

export const ZOOM_SET = 'ZOOM_SET'
export const ZOOM_RESET = 'ZOOM_RESET'
export const ZOOM_ENABLE = 'ZOOM_ENABLE'


