name: Verify, build Docker image, and push to ACR

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feature/*'
      - 'feat/*'

  workflow_dispatch:
    inputs:
      reason:
        description: 'Why are you manually building an image?'
        required: true
        default: 'Because...'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: build server image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          build-args: |
            DB_HOST=${{ secrets.DB_HOST }} 
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
          tags: octoio.azurecr.io/q2behave-server:latest
